swagger: '2.0'
info:
  description: This document lists all the rest apis for TBUK PSD2 Services
  version: 1.0-SNAPSHOT
  title: TBUK Open Banking/PSD2 APIs
host: 'localhost:8090'
basePath: /
tags:
  - name: payment-initiation-service
    description: Payment Initiation Service
  - name: auth-service
    description: Authorisation Service
  - name: account-information-service
    description: Account Information Service
paths:
  '/AccountInformation/getAccountDetail/{accountId}':
    get:
      tags:
        - account-information-service
      summary: getAccountDetail
      operationId: getAccountDetailUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
        - name: accountId
          in: path
          description: accountId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AccountDetail'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/AccountInformation/getAccountTransactions/{accountId}/{dateFrom}/{dateTo}':
    get:
      tags:
        - account-information-service
      summary: getAccountTransactions
      operationId: getAccountTransactionsUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
        - name: accountId
          in: path
          description: accountId
          required: true
          type: string
        - name: dateFrom
          in: path
          description: dateFrom
          required: true
          type: string
        - name: dateTo
          in: path
          description: dateTo
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountTransaction'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /AccountInformation/getAccountsList:
    get:
      tags:
        - account-information-service
      summary: getAccounts
      operationId: getAccountsUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/BankAccount'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/AccountInformation/getBalance/{accountId}':
    get:
      tags:
        - account-information-service
      summary: getBalance
      operationId: getBalanceUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
        - name: accountId
          in: path
          description: accountId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: number
            format: double
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/AccountInformation/getStatement/{accountId}/{month}/{year}':
    get:
      tags:
        - account-information-service
      summary: getStatement
      operationId: getStatementUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
        - name: accountId
          in: path
          description: accountId
          required: true
          type: string
        - name: month
          in: path
          description: month
          required: true
          type: integer
          format: int32
        - name: year
          in: path
          description: year
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Statement'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /Auth/getAuthorisation:
    get:
      tags:
        - auth-service
      summary: getAuthorisation
      operationId: getAuthorisationUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/BankAuthorization'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/Auth/getPaymentUID/{accountId}':
    get:
      tags:
        - auth-service
      summary: getPaymentUID
      operationId: getPaymentUIDUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
        - name: accountId
          in: path
          description: accountId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PaymentUID'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /PaymentInitiation/domesticPayment:
    post:
      tags:
        - payment-initiation-service
      summary: domesticPayment
      operationId: domesticPaymentUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
        - in: body
          name: payementRequest
          description: payementRequest
          required: true
          schema:
            $ref: '#/definitions/PaymentInitiationRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PaymentResult'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /PaymentInitiation/internationalPayment:
    post:
      tags:
        - payment-initiation-service
      summary: internationalPayment
      operationId: internationalPaymentUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
        - in: body
          name: payementRequest
          description: payementRequest
          required: true
          schema:
            $ref: '#/definitions/PaymentInitiationRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PaymentResult'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/PaymentInitiation/paymentStatusEnquiry/{transactionId}':
    get:
      tags:
        - payment-initiation-service
      summary: paymentStatusEnquiry
      operationId: paymentStatusEnquiryUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
        - name: transactionId
          in: path
          description: transactionId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PaymentResult'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /PaymentInitiation/transferBetweenAccounts:
    post:
      tags:
        - payment-initiation-service
      summary: transferBetweenAccounts
      operationId: transferBetweenAccountsUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: audience
          in: query
          required: false
          type: string
        - name: client_Id
          in: query
          required: false
          type: string
        - name: content_Type
          in: query
          required: false
          type: string
        - name: x_fapi_customer_ip_address
          in: query
          required: false
          type: string
        - name: nonce
          in: query
          required: false
          type: string
        - in: body
          name: payementRequest
          description: payementRequest
          required: true
          schema:
            $ref: '#/definitions/PaymentInitiationRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PaymentResult'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  PaymentInfo:
    type: object
    properties:
      charge:
        $ref: '#/definitions/Charge'
      convertedAmount:
        type: number
        format: double
      instructedAmount:
        type: number
        format: double
      instructedCurrency:
        type: string
        enum:
          - GBP
          - USD
          - TRY
          - EUR
      rate:
        type: number
        format: double
  Address:
    type: object
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      postCode:
        type: string
  Statement:
    type: object
    properties:
      base64StatementFile:
        type: string
      fileName:
        type: string
      statementDate:
        type: string
        format: date
  PaymentResult:
    type: object
    properties:
      error:
        $ref: '#/definitions/Error'
      paymentInfo:
        $ref: '#/definitions/PaymentInfo'
      referenceId:
        type: string
      status:
        type: string
        enum:
          - INVALID_STATUS
          - PENDING
          - PROCESSING
          - SUCCESS
          - PENDING_EXTERNAL_AUTHORIZATION
          - FAILURE_INSUFFICIENT_FUNDS
          - FAILURE_GENERIC
          - SENT
          - INITIATED
      transactionId:
        type: string
  Charge:
    type: object
    properties:
      amount:
        type: number
        format: double
      chargeName:
        type: string
      currency:
        type: string
        enum:
          - GBP
          - USD
          - TRY
          - EUR
      tax:
        type: number
        format: double
  PaymentInitiationRequest:
    type: object
    properties:
      creditor:
        $ref: '#/definitions/BankAccount'
      debtor:
        $ref: '#/definitions/BankAccount'
      grpHdr:
        $ref: '#/definitions/GrpHdr'
      instructedAmount:
        $ref: '#/definitions/InstructedAmount'
      remittanceInfo:
        $ref: '#/definitions/RemittanceInfo'
  BankAuthorization:
    type: object
    properties:
      bankAccounts:
        type: array
        items:
          $ref: '#/definitions/BankAccount'
      psuMember_id:
        type: string
  Error:
    type: object
    properties:
      errorCode:
        type: string
      errorText:
        type: string
      httpErrorCode:
        type: integer
        format: int32
  BankAccount:
    type: object
    properties:
      accountId:
        type: string
      accountNo:
        type: string
      accountSubType:
        type: string
        enum:
          - CURRENT_ACCOUNT
          - NOTICE_ACCOUNT
          - TIME_DEPOSITS
      address:
        $ref: '#/definitions/Address'
      bicCode:
        type: string
      currency:
        type: string
        enum:
          - GBP
          - USD
          - TRY
          - EUR
      iban:
        type: string
      name:
        type: string
      sortCode:
        type: string
      statementAvailable:
        type: boolean
  AccountTransaction:
    type: object
    properties:
      amount:
        type: number
        format: double
      chargeInfo:
        $ref: '#/definitions/Charge'
      currency:
        type: string
        enum:
          - GBP
          - USD
          - TRY
          - EUR
      description:
        type: string
      from:
        $ref: '#/definitions/BankAccount'
      referenceId:
        type: string
      status:
        type: string
        enum:
          - INVALID_STATUS
          - PENDING
          - PROCESSING
          - SUCCESS
          - PENDING_EXTERNAL_AUTHORIZATION
          - FAILURE_INSUFFICIENT_FUNDS
          - FAILURE_GENERIC
          - SENT
          - INITIATED
      to:
        $ref: '#/definitions/BankAccount'
      transactionId:
        type: string
  Date:
    type: object
    properties:
      day:
        type: integer
        format: int32
      month:
        type: integer
        format: int32
      year:
        type: integer
        format: int32
  DateTime:
    type: object
    properties:
      day:
        type: integer
        format: int32
      hour:
        type: integer
        format: int32
      minute:
        type: integer
        format: int32
      month:
        type: integer
        format: int32
      second:
        type: integer
        format: int32
      year:
        type: integer
        format: int32
  GrpHdr:
    type: object
    properties:
      creDtTm:
        $ref: '#/definitions/DateTime'
      referenceId:
        type: string
  AccountDetail:
    type: object
    properties:
      balance:
        type: number
        format: double
      bankAccount:
        $ref: '#/definitions/BankAccount'
  RemittanceInfo:
    type: object
    properties:
      unstructuredData:
        type: string
  PaymentUID:
    type: object
    properties:
      paymentUID:
        type: string
  InstructedAmount:
    type: object
    properties:
      amount:
        type: number
        format: double
      currency:
        type: string
        enum:
          - GBP
          - USD
          - TRY
          - EUR
